# Generated by Django 5.0 on 2024-11-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='arrived_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='left_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
