# Generated by Django 5.0 on 2024-11-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_alter_attendence_arrived_at_alter_attendence_left_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='time',
            field=models.TimeField(),
        ),
    ]
