# Generated by Django 5.0 on 2024-11-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_alter_group_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='status',
            field=models.CharField(choices=[('at time', 'at time'), ('late', 'late')], default='at time', max_length=50),
            preserve_default=False,
        ),
    ]
