# Generated by Django 5.0 on 2024-11-23 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0004_attendence_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='not_come',
        ),
        migrations.AlterField(
            model_name='attendence',
            name='status',
            field=models.CharField(choices=[('at time', 'at time'), ('late', 'late'), ('not came', 'not came')], max_length=50),
        ),
        migrations.CreateModel(
            name='Apsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.student')),
            ],
        ),
    ]
